# Generated by Django 3.1 on 2020-09-04 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(default=None)),
                ('status', models.CharField(choices=[('N', 'New'), ('INP', 'Inprogress'), ('D', 'Done'), ('INV', 'Invalid')], default='N', max_length=3)),
                ('assignedto', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedto', to=settings.AUTH_USER_MODEL)),
                ('completedby', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completedby', to=settings.AUTH_USER_MODEL)),
                ('ticketfiler', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ticketfiler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
